language: cpp

compiler:
    - g++-4.8

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update

install:
    - sudo apt-get install g++-4.8 && export CXX=g++-4.8
    - sudo apt-get install libgtkmm-3.0-dev

# build for gtkmm only
before_script:
    - mkdir TemplatiousLib
    - pushd TemplatiousLib
    - git clone https://github.com/davidkazlauskas/templatious.git
    - popd
    - pushd GTKMM-NthPrimeNumberGenerator
    - mkdir build
    - pushd build
    - cmake ..

script: make

env:
    - TEMPLATIOUS_DIR=$TRAVIS_BUILD_DIR/TemplatiousLib

os:
    - linux
